
NumberOfParticles: 5
AllParticles: &allParticles [1, 2, 3, 4, 5]

TreeName: kbicker/USR55

TreeBranches:
    onePerEvent:
        double:
            - &X_primV X_primV
            - &Y_primV Y_primV
            - &Z_primV Z_primV
            - &gradx gradx
            - &grady grady
            - beam_time
            - chi2PV
            - &RPD_Px RPD_Px
            - &RPD_Py RPD_Py
            - &RPD_Pz RPD_Pz
            - &RPD_E RPD_E
            - RPD_Tz
            - RPD_z
            - RPD_beta
            - RPD_Phi
            - RPD_dEA
            - RPD_dEB
            - cedarTheta_X
            - cedarTheta_Y
            - cedarProbK1
            - cedarProbK2
            - cedarProbK3

        int:
            - Run
            - &TrigMask TrigMask
            - SpillNbr
            - &nbrRPDTracks nbrRPDTracks
#            - &isKaon isKaon
            - &isKaon cedarID_bayes

        Long64_t:
            - EvNbr

    onePerParticle:

        double:
            - &Mom_x Mom_x
            - &Mom_y Mom_y
            - &Mom_z Mom_z
            - zmax
            - theta_RICH_

        int:
            - PID_RICH_

Constants:
    ChargedKaonMass: 0.493677
    ChargedPionMass: &ChargedPionMass 0.13957018
    ProtonMass     : 0.938272046

#   old values used by flo
#   ChargedPionMass: 0.9382723
#   ProtonMass     : 0.139567

CalculatedQuantities:

    - Name: &LorentzVecName LorentzVec_
      Function:
          Name: getLorentzVec
          X: *Mom_x
          Y: *Mom_y
          Z: *Mom_z
          M: *ChargedPionMass
      Indices: *allParticles

    - Name: &RPDProton RPDProton
      Function:
          Name: getLorentzVec
          Px: *RPD_Px
          Py: *RPD_Py
          Pz: *RPD_Pz
          E: *RPD_E

    - Name: &RPDProtonMass RPDProtonMass
      Function:
          Name: mass
          Vector: *RPDProton

    - Name: &XLorentzVec XLorentzVec
      Function:
          Name: sum
          Summands:
              Name: *LorentzVecName
              Indices: *allParticles

    - Name: MomSum
      Function:
          Name: sum
          Summands:
              - *Mom_x
              - *Mom_y
              - *Mom_z
      Indices: *allParticles

    - Name: &XMass XMass
      Function:
          Name: mass
          Vector: *XLorentzVec

    - Name: &BeamLV BeamLV
      Function:
          Name: getBeamLorentzVector
          dX: *gradx
          dY: *grady
          XLorentzVec: *XLorentzVec

    - Name: &BeamE BeamE
      Function:
          Name: energy
          Vector: *BeamLV

    - Name: [t, tMin, &tPrime tPrime]
      Function:
          Name: getTs
          BeamLorentzVec: *BeamLV
          XLorentzVec: *XLorentzVec

    - Name: [&rpdDeltaPhiProjection rpdDeltaPhiProjection, &rpdDeltaPhiResProjection rpdDeltaPhiResProjection]
      Function:
        Name: getRpdPhi
        Method: Projection
        BeamLorentzVec: *BeamLV
        RPDProtonLorentzVec: *RPDProton
        XLorentzVec: *XLorentzVec

    - Name: &VertexR VertexR
      Function:
          Name: sum2
          Summands:
              - *X_primV
              - *Y_primV

    - Name: &AbsRpdPhiProjection AbsRpdPhiProjection
      Function:
          Name: abs
          Arg: *rpdDeltaPhiProjection

    - Name: &RpdPhiCutDiffProjection RpdPhiCutDiffProjection
      Function:
          Name: diff
          Minuend: *AbsRpdPhiProjection
          Subtrahend: *rpdDeltaPhiResProjection

Cuts:
#ShortName is the UID

    - &TriggerMaskCut
      ShortName: trigmask_&_0x1
      LongName: Trigger Mask & 0x1
      Abbreviation: Trig&0x1
      Cut:
          Name: TriggerMask
          Type: Inclusive
          Mask: 1
          Variable: *TrigMask

    - &VertexZCut
      ShortName: -29<vtx_z<-66
      LongName: "Vertex Z in ]-29, -66["
      Abbreviation: VtxZ
      Cut:
          Name: Range
          Type: Exclusive
          LowerBound: -66
          UpperBound: -29
          Variable: *Z_primV

    - &VertexRCut
      ShortName: Vtx_R<1.55
      LongName: Vertex.R() < 1.55
      Abbreviation: VtxR
      Cut:
          Name: Range
          Type: Exclusive
          UpperBound: 1.55
          Variable: *VertexR

    - &nRPDTracksCut
      ShortName: nRPDTracks=1
      LongName: 1 RPD Track
      Abbreviation: RPDtr
      Cut:
          Name: Equality
          Type: ==
          Value: 1
          Variable: *nbrRPDTracks

    - &RPDProtonMassCut
      ShortName: p+_mass>0.2
      LongName: RPD's proton mass > 0.2
      Abbreviation: RPDpm
      Cut:
          Name: Range
          Type: Exclusive
          LowerBound: 0.2
          Variable: *RPDProtonMass

    - &KaonCut
      ShortName: IsKaon=0
      LongName: "IsKaon == 0"
      Abbreviation: IsK
      Cut:
          Name: Equality
          Type: ==
          Variable: *isKaon
          Value: 0

    - &TPrimeCut
      ShortName: t_prim
      LongName: "t' in ]0.1, 1.["
      Abbreviation: t'
      Cut:
          Name: Range
          Type: Exclusive
          LowerBound: 0.1
          UpperBound: 1.0
          Variable: *tPrime

    - &RPDPlanarityCut
      ShortName: RpdPlanarity
      LongName: RPD planarity cut
      Abbreviation: RpdPl
      Cut:
          Name: Range
          Type: Exclusive
          UpperBound: *rpdDeltaPhiResProjection
          Variable: *AbsRpdPhiProjection

    - &ExclusivityCut
      ShortName: 187.72<X.E()<195.28
      LongName: "X Energy in ]187.72, 195.28["
      Abbreviation: Excl
      Cut:
          Name: Range
          Type: Exclusive
          LowerBound: 187.72
          UpperBound: 195.28
          Variable: *BeamE

    - &StdKin
      ShortName: Vertex_Z&R
      LongName: Vertex Z and R cuts
      Abbreviation: StdKin
      Cut:
          Name: Group
          Cuts:
              - *VertexZCut
              - *VertexRCut

CutTrains:

    - &StdEvSel
      Name: Standard Event Selection
      Cuts:
          - *TriggerMaskCut
          - *VertexZCut
          - *VertexRCut
          - *TPrimeCut
          - *KaonCut
          - *nRPDTracksCut
          - *RPDProtonMassCut
          - *RPDPlanarityCut
          - *ExclusivityCut
      Pertinent: Yes

    - Name: All Cuts (Debug)
      Cuts:
          - *TriggerMaskCut
          - *VertexZCut
          - *VertexRCut
          - *nRPDTracksCut
          - *RPDProtonMassCut
          - *TPrimeCut
          - *RPDPlanarityCut
          - *ExclusivityCut
          - *StdKin
      Pertinent: No

    - &DebugCutTrain
      Name: Test (Debug)
      Cuts:
          - *KaonCut
          - *VertexRCut
          - *RPDProtonMassCut
          - *RPDPlanarityCut
          - *StdKin
          - *TriggerMaskCut
      Pertinent: No

GlobalPlotOptions:

    PlotsForSequentialCuts: On
    PlotsWithSingleCutsOn: On
    PlotsWithSingleCutsOff: On
    StatisticsHistogram:
        State: On
        InputName: kbicker/statistic
        OutputName: waterfallPlot
    GlobalCuts:
        - CutTrain: *StdEvSel
          WithCuts: [ *TPrimeCut, *KaonCut, [ *nRPDTracksCut, *RPDProtonMassCut ] ]
          WithoutCuts: [ *RPDPlanarityCut, [ *RPDProtonMassCut, *nRPDTracksCut ] ]

Plots:

    - Name: 5_pion_mass
      Variable: *XMass
      LowerBound: 0
      UpperBound: 7
      NBins: 750
      CustomCuts:
          - CutTrain: *DebugCutTrain
            WithCuts: [ *KaonCut, [ *StdKin, *RPDPlanarityCut ] ]
            WithoutCuts: [ *StdKin ]

    - Name: Vertex Distribution
      Variables: [ *X_primV, *Y_primV ]
      LowerBounds: [ -5, -5 ]
      UpperBounds: [ 5, 5 ]
      NBins: [ 1000, 1000 ]

