
NumberOfParticles: 5
AllParticles: &allParticles [1, 2, 3, 4, 5]

TreeName: kbicker/USR55

TreeBranches:
    onePerEvent:
        double:
            - X_primV
            - Y_primV
            - Z_primV
            - gradx
            - grady
            - beam_time
            - chi2PV
            - RPD_Px
            - RPD_Py
            - RPD_Pz
            - RPD_E
            - RPD_Tz
            - RPD_z
            - RPD_beta
            - RPD_Phi
            - RPD_dEA
            - RPD_dEB
            - cedarTheta_X
            - cedarTheta_Y
            - cedarProbK1
            - cedarProbK2
            - cedarProbK3

        int:
            - Run
            - TrigMask
            - SpillNbr
            - nbrRPDTracks
#           - isKaon
            - cedarID_bayes

        Long64_t:
            - EvNbr

    onePerParticle:

        double:
            - &Mom_x Mom_x
            - &Mom_y Mom_y
            - &Mom_z Mom_z
            - zmax
            - theta_RICH_

        int:
            - PID_RICH_

Constants:
    ChargedKaonMass: 0.493677
    ChargedPionMass: &ChargedPionMass 0.13957018
    ProtonMass     : 0.938272046

#   old values used by flo
#   ChargedPionMass: 0.9382723
#   ProtonMass     : 0.139567

CalculatedQuantities:

    - Name: &LorentzVecName LorentzVec_
      Function:
          Name: getLorentzVec
          X: *Mom_x
          Y: *Mom_y
          Z: *Mom_z
          M: *ChargedPionMass
      Indices: *allParticles

    - Name: &TotalLorentzVec TotalLorentzVec
      Function:
          Name: sum
          Summands:
              Name: *LorentzVecName
              Indices: *allParticles

    - Name: MomSum
      Function:
          Name: sum
          Summands:
              - *Mom_x
              - *Mom_y
              - *Mom_z
      Indices: *allParticles

    - Name: XMass
      Function:
          Name: mass
          Vector: *TotalLorentzVec

Cuts:

    RangeCut:
        Variable: *Mom_x
        LowerBound: -1
        UpperBound: 1

